# Database settings.
#database:
#  # the name of your JDBC driver
#  driverClass: org.h2.Driver
#
#  # the username
#  user: sa
#
#  # the password
#  password: sa
#
#  # the JDBC URL
#  url: jdbc:h2:./target/example

database:
  # the name of your JDBC driver
  driverClass: org.gjt.mm.mysql.Driver

  # the username
  user: root

  # the password
  password: 1234

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/authorization

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  type: simple
  connector:
    type: http
    port: 3000
  applicationContextPath: /

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
#    com.example.app: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console

clientSecrets:
    facebook: f17dd0df27c2d7ab6c5192d5de132d92
#    facebook: 298fb6c080fda239b809ae418bf49700
    google: xGxxgKAObIRUwOKycySkL9Fi
    linkedin: Linkedin Client Secret
    github: Github Client Secret
    foursquare: Foursquare Secret
    twitter: Twitter Consumer Key
    